name: Generic Issue
description: Open generic issue
title: "Generic Issue"
labels: [triage]
assignees:
  - matteobruni
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: custom-request
    attributes:
      label: What do you need?
      description: Also tell us, do you have some issues?
      placeholder: Tell us everything we can to do help you!
      value: "I need help!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: Version (eg. 1.0.0)
    validations:
      required: true
  - type: dropdown
    id: library
    attributes:
      label: Which library are you using?
      multiple: true
      options:
        - Vanilla (tsparticles)
        - React.js (@tsparticles/react)
        - Vue.js 2.x (@tsparticles/vue2)
        - Vue.js 3.x (@tsparticles/vue3)
        - Angular (@tsparticles/angular)
        - Svelte (@tsparticles/svelte)
        - jQuery (@tsparticles/jquery)
        - Preact (@tsparticles/preact)
        - Solid (@tsparticles/solid)
        - Riot.js (@tsparticles/riot)
        - Inferno (@tsparticles/inferno)
        - Web Components (@tsparticles/webcomponents)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/matteobruni/tsparticles/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
